eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://host.docker.internal:8761/eureka}
      
okta:
  oauth2:
    issuer: https://dev-64339550.okta.com/oauth2/default
    audience: api://default


spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
